const API_BASE_URL_DEVELOPMENT='https://localhost:7253'; 
const API_BASE_URL_PRODUCTION='https://appname.azurewebsites.net'; 

const ENDPOINTS={
    GET_ALL_USERS:'api/User',
    GET_USER_BY_ID:'api/User/id?id=',
    CREATE_USER:'api/User',
    UPDATE_USER:'api/User/id',
    DELETE_USER_BY_ID:'api/User/id?id='
};

const development={
    API_URL_GET_ALL_USERS:`${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_ALL_USERS}`,
    API_URL_GET_USER_BY_ID:`${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_USER_BY_ID}`,
    API_URL_CREATE_USER:`${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.CREATE_USER}`,
    API_URL_UPDATE_USER:`${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.UPDATE_USER}`,
    API_URL_DELETE_USER_BY_ID:`${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.DELETE_USER_BY_ID}`,


};

const production={
    API_URL_GET_ALL_USERS:`${API_BASE_URL_PRODUCTION}/${ENDPOINTS.GET_ALL_USERS}`,
    API_URL_GET_USER_BY_ID:`${API_BASE_URL_PRODUCTION}/${ENDPOINTS.GET_USER_BY_ID}`,
    API_URL_CREATE_USER:`${API_BASE_URL_PRODUCTION}/${ENDPOINTS.CREATE_USER}`,
    API_URL_UPDATE_USER:`${API_BASE_URL_PRODUCTION}/${ENDPOINTS.UPDATE_USER}`,
    API_URL_DELETE_USER_BY_ID:`${API_BASE_URL_PRODUCTION}/${ENDPOINTS.DELETE_USER_BY_ID}`,


};

const Constant=process.env.NODE_ENV ==='development' ? development: production;

export default Constant;